GMAIL_USERNAME: 'GMAIL_USERNAME'
GMAIL_PASSWORD: 'GMAIL_PASSWORD'
FACEBOOK_APP_ID: 'FACEBOOK_APP_ID'
FACEBOOK_APP_ID: 'FACEBOOK_APP_ID'
TWITTER_APP_ID: 'TWITTER_APP_ID'
TWITTER_APP_SECRET: 'TWITTER_APP_SECRET'
